### ISSUE TITLE
Speech-to-text with publicly available deep learning models

### ISSUE THREAD

**Issue by ArenaGrenade** [jitsi/gsoc-ideas#12]
Hi!
I have read through the idea document for "Speech-to-text with publicly available deep learning models". But, one thing I feel is missing there: Will the inference servers have a GPU available to them? Meaning will Jigasi be using a GPU enabled instance to run?

Because, the choice of a specific model complexity would be decided based on the resources available. Though, we can run these heavy and high-performance models on CPU instances, we might not get the low latency required in the process. So, deciding the instance type early can help in choice of models and so on.

**Comment by nikvaessen** [comment]
Hi,

This is definitely an important design decision. We need to consider 

1) performance, e.g. word-error-rate, 
2) usability, e.g. near-real time results, and
3) costs, e.g. complexity of development, and resource costs

In order to make this decision, it would be prudent to research various options, and their associated performance and inference speed (on CPU and GPU).

**Comment by ArenaGrenade** [comment]
Hey @nikvaessen I was wondering if you are planning to start reviewing any proposals before the official gsoc timeline. Some orgs do this and ask for some take homes.
